#!/bin/bash
# Diagnostic script for Fly.io deployment issues
# Run this locally to check what Fly should have configured

echo "=== Fly.io Diagnostic Checklist ==="
echo ""
echo "Step 1: Check Fly logs (run in your terminal):"
echo "  fly logs -a gary-asst --since 60m"
echo ""
echo "Then reload: https://gary-asst.fly.dev/digest/preview?source=live&date=2026-02-18&mailbox=chintan.panchal@rpck.com"
echo ""
echo "Look for these log lines:"
echo "  - 'Preview request received: source=live, date=2026-02-18, mailbox=chintan.panchal@rpck.com'"
echo "  - 'Selecting calendar provider: ... (from CALENDAR_PROVIDER env var)'"
echo "  - 'Using calendar provider: MSGraphAdapter' (should be this, not MockCalendarProvider)"
echo "  - 'MS Graph token request' or 'GRAPH REQUEST'"
echo "  - 'GRAPH RESPONSE STATUS: 200' (should be 200, not 401/403)"
echo "  - 'Received X events from provider'"
echo "  - 'Mapped to X meetings'"
echo ""
echo "Step 2: Check Fly secrets:"
echo "  fly secrets list -a gary-asst"
echo ""
echo "Step 3: Check Fly status:"
echo "  fly status -a gary-asst"
echo ""
echo "Expected secrets:"
echo "  - CALENDAR_PROVIDER=ms_graph"
echo "  - AZURE_CLIENT_ID=..."
echo "  - AZURE_CLIENT_SECRET=..."
echo "  - AZURE_TENANT_ID=..."
echo "  - ALLOWED_MAILBOXES=chintan.panchal@rpck.com,..."
echo ""
echo "Step 4: If CALENDAR_PROVIDER is missing or wrong:"
echo "  fly secrets set -a gary-asst CALENDAR_PROVIDER=ms_graph"
echo "  fly deploy -a gary-asst"
echo ""
echo "Step 5: If Azure secrets are missing:"
echo "  fly secrets set -a gary-asst AZURE_CLIENT_ID=your-client-id"
echo "  fly secrets set -a gary-asst AZURE_CLIENT_SECRET=your-secret"
echo "  fly secrets set -a gary-asst AZURE_TENANT_ID=your-tenant-id"
echo "  fly deploy -a gary-asst"
echo ""
